AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: auth

Parameters:
  DomainName:
    Type: String
  Certificate:
    Type: String

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: False
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: False
          TemporaryPasswordValidityDays: 7
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPool
      Domain: !Ref DomainName
      CustomDomainConfig:
        CertificateArn: !Ref Certificate

  UserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/stack/${AWS::StackName}/UserPoolId"
      Value: !Ref UserPool

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ClientId
          AttributeType: S
      KeySchema:
        - AttributeName: ClientId
          KeyType: HASH

  ProductTableReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
            Resource:
              - !GetAtt ProductTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt ProductTable.Arn }

  RestrictionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH

  RestrictionTableReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
            Resource:
              - !GetAtt RestrictionTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt RestrictionTable.Arn }

  PreSignupFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda/presignup/
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - !Ref ProductTableReadOnlyPolicy
        - !Ref RestrictionTableReadOnlyPolicy
      Events:
        CognitoEvent:
          Type: Cognito
          Properties:
            UserPool: !Ref UserPool
            Trigger: PreSignUp
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          PRODUCT_TABLE: !Ref ProductTable
          RESTRICTION_TABLE: !Ref RestrictionTable

  PreAuthenticationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: lambda/preauth/
      Handler: bootstrap
      Runtime: provided.al2
      Policies:
        - !Ref ProductTableReadOnlyPolicy
        - !Ref RestrictionTableReadOnlyPolicy
      Events:
        CognitoEvent:
          Type: Cognito
          Properties:
            UserPool: !Ref UserPool
            Trigger: PreAuthentication
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          PRODUCT_TABLE: !Ref ProductTable
          RESTRICTION_TABLE: !Ref RestrictionTable

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolIdSSM:
    Value: !Ref UserPoolId
  RestrictionTable:
    Value: !Ref RestrictionTable
  ProductTable:
    Value: !Ref ProductTable
